[[test]]
test_id = "1.1"
test_group = "1:POINT_CLOUD"
test_priority = "MEDIUM"
test_description = "Check that point cloud is being displayed correctly for 2 minutes (Both indoor/outdoor setting) using STDV format (pixel_format=0)"
pass_condition = "Accurate image representation of what the sensor is viewing"
instructions = [
  "## Ensure the sensor has default configuration ##",
  "## Set pixel format to STDV (0) ##",
  " set pixel_format=0",
  "## Turn on point enable and MST ##",
  "set point_enable=1, drive_big_mirror=1",
  "## Observe display for 2 minutes ##"
]
test_authors_and_contact_persons = [
  "Rishi Bahadoor",
]

[[test]]
test_id = "1.2"
test_group = "1:POINT_CLOUD"
test_priority = "MEDIUM"
test_description = "Check that point cloud is being displayed correctly for 2 minutes (Both indoor/outdoor setting) using HRAD format (pixel_format=2)"
pass_condition = "Accurate image representation of what the sensor is viewing"
instructions = [
  "## Ensure the sensor has default configuration ##",
  "## Set pixel format to HRAD (2) ##",
  " set pixel_format=2",
  "## Turn on point enable and MST ##",
  "set point_enable=1, drive_big_mirror=1",
  "## Observe display for 2 minutes ##"
]
test_authors_and_contact_persons = [
  "Rishi Bahadoor",
]

[[test]]
test_id = "1.3"
test_group = "1:POINT_CLOUD"
test_priority = "MEDIUM"
test_description = "Check that point cloud is being displayed correctly for 2 minutes (Both indoor/outdoor setting) using HLZ4 format (pixel_format=3)"
pass_condition = "Accurate image representation of what the sensor is viewing"
instructions = [
  "## Ensure the sensor has default configuration ##",
  "## Set pixel format to HLZ4 (3) ##",
  " set pixel_format=3",
  "## Turn on point enable and MST ##",
  "set point_enable=1, drive_big_mirror=1",
  "## Observe display for 2 minutes ##"
]
test_authors_and_contact_persons = [
  "Rishi Bahadoor",
]

[[test]]
test_id = "1.4"
test_group = "1:POINT_CLOUD"
test_priority = "HIGH"
test_description = "Check per point stability that is points do not flicker"
pass_condition = "No flickering on the display of the point cloud"
instructions = [
  "## Ensure the sensor has default configuration ##",
  "## Set pixel format to each pixel format per observation##",
  " set pixel_format=(specific_pixel_format)",
  "## Turn on point enable and MST ##",
  "set point_enable=1, drive_big_mirror=1",
  "## Observe display for 2 minutes ##"
]
test_authors_and_contact_persons = [
  "Rishi Bahadoor",
]
