name: Rust CI (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install 7zip
      shell: pwsh
      run: |
        choco install 7zip -y

    - name: Download Npcap SDK
      run: curl.exe -L -o npcap-sdk.zip https://npcap.com/dist/npcap-sdk-1.05.zip

    - name: Extract SDK with 7zip
      run: |
        mkdir npcap-sdk
        & "C:\Program Files\7-Zip\7z.exe" x npcap-sdk.zip -onpcap-sdk

    - name: Verify wpcap.lib presence
      shell: pwsh
      run: |
        dir "${{ github.workspace }}\\npcap-sdk\\Lib"
        if (!(Test-Path "${{ github.workspace }}\\npcap-sdk\\Lib\\wpcap.lib")) {
          Write-Error "wpcap.lib not found in SDK Lib directory"
        }

    - name: Set NPCAP env vars
      run: |
        echo "NPCAP_INCLUDE=${{ github.workspace }}\\npcap-sdk\\Include" >> $env:GITHUB_ENV
        echo "NPCAP_LIB=${{ github.workspace }}\\npcap-sdk\\Lib\\x64" >> $env:GITHUB_ENV

    - name: Build in release mode
      env:
        LIB: ${{ env.NPCAP_LIB }}
        INCLUDE: ${{ env.NPCAP_INCLUDE }}
        LIBPCAP_LIBDIR: ${{ env.NPCAP_LIB }}
      run: cargo build --release

    - name: Run tests
      env:
        LIB: ${{ env.NPCAP_LIB }}
        INCLUDE: ${{ env.NPCAP_INCLUDE }}
        LIBPCAP_LIBDIR: ${{ env.NPCAP_LIB }}
      run: cargo test